import { Grid } from "@mui/material";
import CategorySidebar from "@/components/modules/categoryPage/CategorySidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "دیوار",
  description: "Generated by create next app",
};

export default function CategoryLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Grid container display="flex" spacing={2} marginTop={3}>
      <CategorySidebar />
      <Grid item container spacing={2} sm={12} md={9} lg={10} alignContent="start">
        {children}
      </Grid>
    </Grid>
  );
}
